---
abstract: 'wraps Net::SFTP::Foreign to throw exceptions on failure'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SFTP-Foreign-Exceptional
requires:
  Carp: 0
  Class::Inspector: 0
  English: 0
  Moose: 0
  Net::SFTP::Foreign: 1.65
  Readonly: 0
  perl: 5.008
  utf8: 0
resources:
  bugtracker: https://github.com/mjgardner/net-sftp-foreign-exceptional/issues
  homepage: http://search.cpan.org/dist/Net-SFTP-Foreign-Exceptional/
  repository: git://github.com/mjgardner/net-sftp-foreign-exceptional.git
version: 0.004
