---
abstract: 'wraps Net::SFTP::Foreign to throw exceptions on failure'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Deep: 0
  Test::More: 0.94
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SFTP-Foreign-Exceptional
requires:
  Any::Moose: 0
  Carp: 0
  English: 0
  Net::SFTP::Foreign: 1.67
  Package::DeprecationManager: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/mjgardner/net-sftp-foreign-exceptional/issues
  homepage: http://metacpan.org/release/Net-SFTP-Foreign-Exceptional/
  repository: git://github.com/mjgardner/net-sftp-foreign-exceptional.git
version: 0.011
